version: '2'
services:

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - site1app
      - site2app
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - site1files
      - site2files

  site1app:
    build: .
    working_dir: /var/www
    volumes_from:
      - site1files

  site2app:
    build: .
    working_dir: /var/www
    volumes_from:
      - site2files

  site1files:
    image: busybox
    volumes:
      - ./site1:/var/www/site1

  site2files:
    image: busybox
    volumes:
      - ./site2:/var/www/site2
